# Generated by Django 6.0.6 on 2026-08-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nidcheck", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nidcheck",
            name="is_exposed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nidcheck",
            name="match_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
